### ISSUE TITLE
Adding XP For Buying Shipments?

### ISSUE THREAD

**Issue by SpixBox** [sbd/Leveling-System#98]
Hi, just a question. I was wondering if there was a way to implement an XP reward for buying shipments? I tried this myself and only got errors, i'm not at all familiar with lua, but here's what I tried:

`        onBought = function( ply, price ) 
		ply:addXP(0.1 * price)
end`

The result was just two callback errors and two unknown errors.

**Comment by vrondakis** [comment]
What are the exact errors

**Comment by SpixBox** [comment]
attempt to perform arithmetic on local 'price' <a table value>
1. onBought - (my shipments file)
2. callback in gamemodes/darkrp/gamemode/modules/base/sv_purchasing.lua:88
3. callback in gamemodes/darkrp/gamemode/modules/chat/sv_chat.lua:17
4. unknown in gamemode/darkrp/gamemode/modules/chat/sv_chat.lua:256
5. unknown in lua/includes/modules/concommand.lua:54
(Here's a screenshot of the console):

![console](https://user-images.githubusercontent.com/52551956/61161491-cbb3b280-a4b8-11e9-8ec5-5d70fb887b49.PNG)

**Comment by sbd** [comment]
Make a new issue if you still need help
